config/routes.rb
Rails.application.routes.draw do
  get 'appointments/index'
  get 'patients/index'
  get 'physicians/index'
  resources :sharks
  get 'endangered/index'
  get 'endangered/data', to: 'endangered#data'
  post 'endangered/upload', to: 'endangered#upload'
  post 'endangered/destroy', to: 'endangered#destroy'



  get 'reviews/index'
  get 'cards/index'
 # get 'homes/index'
  get 'books/index'
  get 'creators/index'
  get 'resources/index'
  namespace :form_validations do
    get 'posts2/index'
  end
  get 'searches/index'
  get 'homes/post'
  get 'homes/post_data'
 


  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/articles", to: "articles#index"
  # Defines the root path route ("/")
  # root "articles#index
  #get "/searches", to: "searches#index"
  #root "posts#index"
  resources :searches
    resources :posts2
    namespace :form_validations do
      resources :posts2
    end

    resources :resources do 
      resources :creators
    end

    resources :books do
      collection do
        get :search
      end
    end

  resources :articles do
    resources :comments
  end
  resources :users do
    resources :posts
  end

  resources :cards do
    resources :reviews
  end

  #resources :patients 

  root "patients#index"
  get "/patient", to: "patients#create"
  #get "/physicians", to: "physicians#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :patients do
    resources :physicians 
      resources :appointments
  end
  
  
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :physician
    belongs_to :patient
    accepts_nested_attributes_for :physician
    accepts_nested_attributes_for :patient
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
    validates_presence_of :title, :isbn

    searchable do
      text :title
    end
end

app/models/card.rb
class Card < ApplicationRecord
    has_many_attached :images

    has_many :reviews
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/creator.rb
class Creator < ApplicationRecord
end

app/models/endangered.rb
class Endangered < ApplicationRecord
Date of extract: 
<%= Date.today %>
<br>

Posts count:
<%= @sharks.count %>
<br>

<table style="width:100%">
  <thead>
    <tr>
      <th>id
      <th>name</th>
      <th>fact</th>
    </tr>
  </thead>
  <tbody>
    <% @sharks.each do |shark| %>
      <%= content_tag :tr, id: dom_id(post), class: dom_class(post) do %>
        <td><%= shark.name %></td>
        <td><%= shark.fact%></td>
      <% end %>
    <% end %>
  </tbody>
</table> 
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments
    has_many :physicians, through: :appointments
end

app/models/physician.rb
class Physician < ApplicationRecord
    has_many :appointments
    has_many :patients, through: :appointments
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/post2.rb
class Post2 < ApplicationRecord
  validates :body, length: { minimum: 10 }
  validates :title, presence: true
end

app/models/resource.rb
class Resource < ApplicationRecord
    has_many :creators

searchable do
    text :title, :default_boost => 2
    text :description
    text :creators do     # for associations
      creators.map { |creator| creator.name }
    end
    text :tag_list, :default_boost => 2
    time :created_at
  end
end

app/models/review.rb
class Review < ApplicationRecord
 belongs_to :card

#  validates :rating, presence: true, numericality:
#  { greater_than_or_equal_to: 1, less_than_or_equal_to: 5,
#    only_integer: true }

#     after_commit :update_reviewable_rating, on: [:create, :update, :destroy]

#    def update_reviewable_rating
#     reviewable.update! average_rating: reviewable.reviews.average(:rating)
#     # avg + (rating - avg) / count
#   end
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/shark.rb
require 'csv'
class Shark < ApplicationRecord
    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
          csv << column_names
          all.each do |shark|
            csv << shark.attributes.values_at(*column_names)
          end
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts

    def self.user_count
        puts "User count at #{Time.now} is : #{User.count}"
    end
    
    def self.user_name
        puts "User count at #{Time.now} is : #{User.last.name}"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
        # respond_to do |format|
        #     format.js { flash[:info] = "The article with an ID of #{@article.id} has had their admin attribute toggled!" }
        #   end
    end
      
    def show
        @user = User.find(params[:id])
        respond_to do |format|
            format.js { } 
        end  
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        #respond_to do |format|
        if @user.save
            # respond_to do |format|
            #    format.js { flash[:info] = "The user with an name of #{@user.name} has created!" }
            # end
        else
            render :new, status: :unprocessable_entity
      end
    end
    
    def edit
        @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
        if @user.update(user_params)
            # redirect_to @article
            # respond_to do |format|
            #    format.js { flash[:info] = "The user with an ID of #{@user.id} has had their admin attribute toggled!" }
            # end
        else
            render :edit, status: :unprocessable_entity
        end
    end
      
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        # respond_to do |format|
        #     format.html { redirect_to user_url }
        #     # format.json { head :no_content }
        #     format.js   { render :layout => false }
        # end
    end
        
    
 private
    def user_params
        params.require(:user).permit(:name)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_flash2.html.erb
<div class="container">
  <% flash.each do |type, msg| %>
    <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show">
      <%= msg %>
    </div>
  <% end %> 
</div>

app/views/users/_form.html.erb
<div class= "font-weight: 300;">
    <%= form_with(model: user, local: false) do |form| %>
        <div class="modal-body">
        <div id="errorArea"></div>
            <div>
                <%= form.label :name %><br>
                <%= form.text_field :name %>
            </div>
        </div> 
        <div class="modal-footer">
            <%= form.submit  class: "btn btn-primary btn-lg" %>
            <button type="button" class="btn btn-secondary btn-lg close-modal" data-bs-dismiss="modal">Close</button>
        </div>  
    <% end %>
</div>

app/views/users/_form2.html.erb
<!--

<%= form.label :user_id %>
<%= form.collection_select(:user_id, User.all, :id, :name, { include_blank: true }, class: "content-search") %>

<!-->
<div class="form-group  row">
                <label class="col-sm-3 col-form-label text-center">Select User:</label>
                  <div class="col-sm-9">
                    <%#= f.collection_select :user_ids, question.question_group.survey_section.organisation.teams, :id, :name, {}, {:class => 'form-control teams-select', multiple: true, style: 'width: 100%'} %>
                  </div>
              </div>

<%= f.select :user_name, User.pluck(:name) %> 

app/views/users/_show.html.erb
<center>
<div id= "user-edit">
<h2 >User_name :<%= @user.name %></h2>
  <%#= link_to "Edit", edit_user_path(@user), remote: :true,  class: 'btn btn-success bs-btn-bg: #6f8557' , data: { bs_toggle: "modal", bs_target: "#user-new" } %><br>
    <%= link_to "Destroy", user_path(@user), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }, remote: :true, class: 'btn btn-success btn-sm' %>


 <%#= link_to 'New post', new_user_post_path(@user), class: "btn btn-primary btn-lg " , data: { bs_toggle: "modal", bs_target: "#post-new", remote: :true } %></td>
<div id= "new-post"></div>
  <div id="postRow">
    <%= render "posts/showpost",post: @post %></div>
  <div> 
    <%= render "posts/newpost",post: @post %>
</div>
 </center>

  <div class="modal fade" id="editPostModal" tabindex="-1" aria-labelledby="editPostModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editPostModalLabel">Edit Post</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
          <div id="post-edit">
        </div>
    </div>
  </div>



<!--
 <div class="modal fade" id="post-new" tabindex="-1" aria-labelledby="NewPostModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="NewPostModalLabel">Create New post</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
                <div id= "user-edit">
            </div>
        </div>
    </div>
    -->

<style>

.p{
  font-size: 1rem;
  color: #234a70;
}

</style>

app/views/users/_showcreate.html.erb
<%= @user.name%>

        <%#=link_to user.name ,user , class:"a", remote: true %>
            <td><%#=link_to "Edit", edit_user_path(user), remote: :true,  class: 'btn btn-success bs-btn-bg: #6F8557' , data: { bs_toggle: "modal", bs_target: "#editUserModal" } %>
     

app/views/users/_user_row.html.erb
<div id="user-edit">
    <tr id="userRow_<%= user.id %>" >
        <td> name:<%= link_to user.name, user, class:"a", remote: :true %></td>
        <td><%#= link_to "Edit", edit_user_path(user), remote: :true,  class: 'btn btn-success bs-btn-bg: #6F8557' , data: { bs_toggle: "modal", bs_target: "#editUserModal" } %></td>
    </tr>
</div>

app/views/users/create.js.erb
alert("create")
<% if @user.errors.any? %>
   $("#errorArea").html("<%= j render("error", user: @user ) %>")
<% else %>
   $("#userTable").html("<%= j render("showcreate", user: @user) %>");
   $(".close-modal").click();
<% end %>

app/views/users/destroy.js.erb
$('#user_id_<%= @user.id %>').hide();

app/views/users/edit.js.erb
alert("edit")
$("#editUserForm").html("<%= j render partial: 'form', locals: { user: @user} %>")

app/views/users/index.html.erb
<div class="container  pb -50 "  >
    <div id="user-edit">
      <div id="userTable"></div>
          <h4 class="size  mt-3"> Users </h4>
            <div class="padding pb 5" ></div>
                <table class="table  table  mb -3  ">
                    <thead>
                        <tr>
                            <th scope="col"  class="table-dark "  width= "1000px" class="align-middle">User Name:</th>
                        </tr>
                    </thead>
                        <tbody class="table-primary" >
                              <% @users.each do |user| %><tr>
        
                              <td id='user_id<%user.id%>'><%=link_to user.name ,user , class:"a", remote: true %></td>
                                    <td><%=link_to "Edit", edit_user_path(user), remote: :true,  class: 'btn btn-success bs-btn-bg: #6F8557' , data: { bs_toggle: "modal", bs_target: "#editUserModal" } %></td></tr>
                              <% end %><tr>
                                    <td style="width:1000%">
                                        <%= link_to 'New User', new_user_path, class: "btn btn-primary  " , data: { bs_toggle: "modal", bs_target: "#user-new", remote: :true } %></td>
                                    </tr>
                        </tbody>
                </table>
        </div>
  </div>  

  <%#= link_to "New user", new_user_path,  remote: :true,  class: 'btn btn-info btn-sm' %>
<div class="modal fade" id="user-new" tabindex="-1" aria-labelledby="NewUserModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="NewUserModalLabel">Create  User</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div id= "user-form">
            </div>
        </div>
    </div>
</div> 

<!-- Modal -->
<div class="modal fade" id="editUserModal" tabindex="-1" aria-labelledby="editUserModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editUserModalLabel">Edit User</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <div id="editUserForm">
      </div>
  </div>
</div>

<div id="flash-message">
    <%= render 'users/flash2' %>
</div>
<div id="user-destroy"></div>




<style>
.a{
  color: #0f5132;
  font-style: oblique;
  font-weight: bold;
}
 .c{
    bs-btn-bg: #198754
 }
  .size
  { font-size: 2.5rem;
    color: #023a20;

  }
  .table{
    width: 1000px;
  }
  .padding{
    padding-bottom: 100px;
    
  }
  
</style>

app/views/users/new.js.erb
alert("new")
$("#user-form").html("<%= j render partial: 'form', locals: { user: @user} %>")

app/views/users/show.js.erb
$("#user-edit").html("<%= j render partial: 'show', locals: { user: @user} %>")

app/views/users/update.js.erb
<% if @user.errors.any? %>
  $("#errorArea").html("<%= j render("error", user: @user ) %>")
<% else %>
   $("#userRow_<%= @user.id %>").html("<%= j render("user_row", user: @user) %>");
   $(".close-modal").click();
<% end %>