config/routes.rb
Rails.application.routes.draw do
  get 'appointments/index'
  get 'patients/index'
  get 'physicians/index'
  resources :sharks
  get 'endangered/index'
  get 'endangered/data', to: 'endangered#data'
  post 'endangered/upload', to: 'endangered#upload'
  post 'endangered/destroy', to: 'endangered#destroy'



  get 'reviews/index'
  get 'cards/index'
 # get 'homes/index'
  get 'books/index'
  get 'creators/index'
  get 'resources/index'
  namespace :form_validations do
    get 'posts2/index'
  end
  get 'searches/index'
  get 'homes/post'
  get 'homes/post_data'
 


  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/articles", to: "articles#index"
  # Defines the root path route ("/")
  # root "articles#index
  #get "/searches", to: "searches#index"
  #root "posts#index"
  resources :searches
    resources :posts2
    namespace :form_validations do
      resources :posts2
    end

    resources :resources do 
      resources :creators
    end

    resources :books do
      collection do
        get :search
      end
    end

  resources :articles do
    resources :comments
  end
  resources :users do
    resources :posts
  end

  resources :cards do
    resources :reviews
  end

  #resources :patients 

  root "patients#index"
  get "/patient", to: "patients#create"
  #get "/physicians", to: "physicians#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :patients do
    resources :physicians 
      resources :appointments
  end
  
  
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :physician
    belongs_to :patient
    accepts_nested_attributes_for :physician
    accepts_nested_attributes_for :patient
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
    validates_presence_of :title, :isbn

    searchable do
      text :title
    end
end

app/models/card.rb
class Card < ApplicationRecord
    has_many_attached :images

    has_many :reviews
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/creator.rb
class Creator < ApplicationRecord
end

app/models/endangered.rb
class Endangered < ApplicationRecord
Date of extract: 
<%= Date.today %>
<br>

Posts count:
<%= @sharks.count %>
<br>

<table style="width:100%">
  <thead>
    <tr>
      <th>id
      <th>name</th>
      <th>fact</th>
    </tr>
  </thead>
  <tbody>
    <% @sharks.each do |shark| %>
      <%= content_tag :tr, id: dom_id(post), class: dom_class(post) do %>
        <td><%= shark.name %></td>
        <td><%= shark.fact%></td>
      <% end %>
    <% end %>
  </tbody>
</table> 
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments
    has_many :physicians, through: :appointments
end

app/models/physician.rb
class Physician < ApplicationRecord
    has_many :appointments
    has_many :patients, through: :appointments
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/post2.rb
class Post2 < ApplicationRecord
  validates :body, length: { minimum: 10 }
  validates :title, presence: true
end

app/models/resource.rb
class Resource < ApplicationRecord
    has_many :creators

searchable do
    text :title, :default_boost => 2
    text :description
    text :creators do     # for associations
      creators.map { |creator| creator.name }
    end
    text :tag_list, :default_boost => 2
    time :created_at
  end
end

app/models/review.rb
class Review < ApplicationRecord
 belongs_to :card

#  validates :rating, presence: true, numericality:
#  { greater_than_or_equal_to: 1, less_than_or_equal_to: 5,
#    only_integer: true }

#     after_commit :update_reviewable_rating, on: [:create, :update, :destroy]

#    def update_reviewable_rating
#     reviewable.update! average_rating: reviewable.reviews.average(:rating)
#     # avg + (rating - avg) / count
#   end
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/shark.rb
require 'csv'
class Shark < ApplicationRecord
    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
          csv << column_names
          all.each do |shark|
            csv << shark.attributes.values_at(*column_names)
          end
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts

    def self.user_count
        puts "User count at #{Time.now} is : #{User.count}"
    end
    
    def self.user_name
        puts "User count at #{Time.now} is : #{User.last.name}"
    end
end

app/controllers/endangered_controller.rb
class EndangeredController < ApplicationController
  before_action :set_endangered, only: [:index, :data]

  def index
    if @endangered.length > 0
      redirect_to endangered_data_path
    else
      render 'index'
    end
  end

  def data
  end

  def upload
    csv_file = File.join Rails.root, 'db', 'sharks.csv'   
    AddEndangeredWorker.perform_async(csv_file)
    redirect_to endangered_data_path, notice: 'Endangered sharks have been uploaded!'
  end

  def destroy
    RemoveEndangeredWorker.perform_async
    redirect_to root_path
  end

  private
  def set_endangered
    @endangered = Endangered.all 
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/endangered_helper.rb
module EndangeredHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/endangered/data.html.erb
<p id="notice"><%= notice %></p>
<h1>Endangered Sharks</h1>
<p>International Union for Conservation of Nature (ICUN) statuses: <b>vu:</b> Vulnerable, <b>en:</b> Endangered, <b>cr:</b> Critically Endangered </p>

<div class="table-responsive">
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th>Name</th>
      <th>IUCN Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @endangered.each do |shark| %>
      <tr>
        <td><%= shark.name %></td>
        <td><%= shark.iucn %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

  <%= form_tag endangered_destroy_path do %>
     <%= submit_tag "Delete Endangered Sharks" %>
  <% end %>
  
  <br>
  <%= link_to "CSV", sharks_path(format: "csv") %> 
  <%= link_to 'New Shark', new_shark_path, :class => "btn btn-primary btn-sm" %> 
  <%= link_to 'Home', home_index_path, :class => "btn btn-primary btn-sm" %>

app/views/endangered/index.html.erb
<h1>Endangered#index</h1>
<p>Find me in app/views/endangered/index.html.erb</p>
<div>
    <div>
<p id="notice"><%= notice %></p>

<h1>Endangered Sharks</h1>

<p>International Union for Conservation of Nature (ICUN) statuses: <b>vu:</b> Vulnerable, <b>en:</b> Endangered, <b>cr:</b> Critically Endangered </p>

<br>

  <%= form_tag endangered_upload_path do %>
  <%= submit_tag "Import Endangered Sharks" %>
  <% end %>

  <br>


<div class="col-lg-6">
            <h3>Sharks are ancient  and SOME are in danger</h3>
            <p>There is evidence to suggest that sharks lived up to 400 million years ago.Without our help, some could disappear soon.</p>
            <p><%= button_to 'Which Sharks Are in Danger?', endangered_index_path, :method => :get,  :class => "btn btn-primary btn-sm"%>
            </p>
        </div>
    </div>
</div>

<%#= link_to 'New Shark', new_shark_path, :class => "btn btn-primary btn-sm" %> <%#= link_to 'Home', home_index_path, :class => "btn btn-primary btn-sm" %>