config/routes.rb
Rails.application.routes.draw do
  get 'appointments/index'
  get 'patients/index'
  get 'physicians/index'
  resources :sharks
  get 'endangered/index'
  get 'endangered/data', to: 'endangered#data'
  post 'endangered/upload', to: 'endangered#upload'
  post 'endangered/destroy', to: 'endangered#destroy'



  get 'reviews/index'
  get 'cards/index'
 # get 'homes/index'
  get 'books/index'
  get 'creators/index'
  get 'resources/index'
  namespace :form_validations do
    get 'posts2/index'
  end
  get 'searches/index'
  get 'homes/post'
  get 'homes/post_data'
 


  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/articles", to: "articles#index"
  # Defines the root path route ("/")
  # root "articles#index
  #get "/searches", to: "searches#index"
  #root "posts#index"
  resources :searches
    resources :posts2
    namespace :form_validations do
      resources :posts2
    end

    resources :resources do 
      resources :creators
    end

    resources :books do
      collection do
        get :search
      end
    end

  resources :articles do
    resources :comments
  end
  resources :users do
    resources :posts
  end

  resources :cards do
    resources :reviews
  end

  #resources :patients 

  root "patients#index"
  get "/patient", to: "patients#create"
  #get "/physicians", to: "physicians#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :patients do
    resources :physicians 
      resources :appointments
  end
  
  
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :physician
    belongs_to :patient
    accepts_nested_attributes_for :physician
    accepts_nested_attributes_for :patient
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
    validates_presence_of :title, :isbn

    searchable do
      text :title
    end
end

app/models/card.rb
class Card < ApplicationRecord
    has_many_attached :images

    has_many :reviews
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/creator.rb
class Creator < ApplicationRecord
end

app/models/endangered.rb
class Endangered < ApplicationRecord
Date of extract: 
<%= Date.today %>
<br>

Posts count:
<%= @sharks.count %>
<br>

<table style="width:100%">
  <thead>
    <tr>
      <th>id
      <th>name</th>
      <th>fact</th>
    </tr>
  </thead>
  <tbody>
    <% @sharks.each do |shark| %>
      <%= content_tag :tr, id: dom_id(post), class: dom_class(post) do %>
        <td><%= shark.name %></td>
        <td><%= shark.fact%></td>
      <% end %>
    <% end %>
  </tbody>
</table> 
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments
    has_many :physicians, through: :appointments
end

app/models/physician.rb
class Physician < ApplicationRecord
    has_many :appointments
    has_many :patients, through: :appointments
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/post2.rb
class Post2 < ApplicationRecord
  validates :body, length: { minimum: 10 }
  validates :title, presence: true
end

app/models/resource.rb
class Resource < ApplicationRecord
    has_many :creators

searchable do
    text :title, :default_boost => 2
    text :description
    text :creators do     # for associations
      creators.map { |creator| creator.name }
    end
    text :tag_list, :default_boost => 2
    time :created_at
  end
end

app/models/review.rb
class Review < ApplicationRecord
 belongs_to :card

#  validates :rating, presence: true, numericality:
#  { greater_than_or_equal_to: 1, less_than_or_equal_to: 5,
#    only_integer: true }

#     after_commit :update_reviewable_rating, on: [:create, :update, :destroy]

#    def update_reviewable_rating
#     reviewable.update! average_rating: reviewable.reviews.average(:rating)
#     # avg + (rating - avg) / count
#   end
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/shark.rb
require 'csv'
class Shark < ApplicationRecord
    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
          csv << column_names
          all.each do |shark|
            csv << shark.attributes.values_at(*column_names)
          end
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts

    def self.user_count
        puts "User count at #{Time.now} is : #{User.count}"
    end
    
    def self.user_name
        puts "User count at #{Time.now} is : #{User.last.name}"
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  
    def index
        @cards = Card.all
        # respond_to do |format|
        #     format.js { flash[:info] = "The article with an ID of #{@card.id} has had their admin attribute toggled!" }
        #   end
    end
      
    def show
  
      @card = Card.find(params[:id])
      respond_to do |format|
        format.js { render(:text => "not implemented") } 
      end
      
    end
    
    def new
        @card = Card.new
    end
    
    def create
        @card = Card.new(card_params)
        #respond_to do |format|
        if @card.save
            respond_to do |format|
               format.js { flash[:info] = "The user with an name of #{@card.name} has created!" }
            end
        else
            render :new, status: :unprocessable_entity
      end
    end
    
    def edit
        @card = Card.find(params[:id])
    end

    def update
      @card = Card.find(params[:id])
        if @card.update(card_params)
            # redirect_to @article
            respond_to do |format|
               format.js { flash[:info] = "The user with an ID of #{@card.id} has had their admin attribute toggled!" }
            end
        else
            render :edit, status: :unprocessable_entity
        end
    end
      
    def destroy
        @card = Card.find(params[:id])
        @card.destroy
        respond_to do |format|
            format.html { redirect_to user_url }
            # format.json { head :no_content }
            format.js   { render :layout => false }
        end
    end 
 private
    def card_params
      params.require(:card).permit(:name,:header,:rating,images: [])
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_card_details.html.erb
<table>
    <tr>
        <td> name:<%= link_to  card.name, card%></td>
    </tr>
</table>

app/views/cards/_editcard.html.erb
<%= form_with model: card do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :header %><br>
    <%= form.text_area :header %><br>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/_form.html.erb
<div class="background"  style="width:50%" >
  <div class="color">
    <h1>New Form </h1>
      <%= form_with(model: card, local: false) do |form| %>
        <div class="modal-body">
        <div id="errorArea"></div>
            <div>
                <%= form.label :name %><br>
                <%= form.text_field :name %>
            </div>

            <div>
                <%= form.label :header %><br>
                <%= form.text_field :header %>
            </div>
            <div>
                <%= form.label :images %><br>
                <%= form.file_field :images, multiple: true,class: "form-control" %><br>
            </div>
        </div> 
        <div class="modal-footer">
            <%= form.submit  class: "btn btn-primary btn-lg" %>
            <button type="button" class="btn btn-secondary btn-lg close-modal" data-bs-dismiss="modal">Close</button>
        </div>  
    <% end %>
  </div>
</div>
<style>
.color{
    color: #3f51b5;
    background-color: #9e9e9e;
}
.background{
   background-color: #9e9e9e;
}
</style>

app/views/cards/_showcard.html.erb
<div style="background-color:#d3d996;  height: 1000px;">
      <div class="container   body" height= "1000px">
        <h1 style="color: #558757;">card Details </h1>
            <div class="container " style="color: black">
                <div class="row ">
                  <div class="col">
                    <h2> Name:</h2><%= @card.name %>
                  </div>
                    <div class="col">
                      <h2> Header:</h2><%= @card.header %>
                    </div>
                    <div class="col">
                        <h2>Ratings : </h2>
                        <div id='rating-stars'>
                          <%= render partial: 'reviews/showreview', review: @review %>
                        </div>
                      </div>
                    </div>
      </div>  
  </div>
    <div><%= render "reviews/form" , review: @review %></div>
<style>
.w{
  width: 100%;
  padding-top: 5px;
}
.b{
  --bs-btn-border-radius: 0.0;
  width: 20%;
}
.body{
  --bs-body-bg: #b0cfcc;
}
.table{
  border-bottom-width: 5px;
  --bs-body-bg: #b0ddb2;
}
.button{
  --bs-btn-border-width:0.0 px;
}

</style>
</div>

app/views/cards/create.js.erb
<% if @user.errors.any? %>
   $("#errorArea").html("<%= j render("error", card: @card ) %>")
<% else %>
   $("#cardTable").html("<%= j render("card_details", card: @card) %>");
   $(".close-modal").click();
<% end %>

app/views/cards/index.html.erb
<div style="background-color:#aecbcf;  height: 1000px;  font-family: Fantasy;" class="pb -5">
<center>
<div id="card-show">
<h1 style="color: #1b68b5 " font-family="Ebrima">Cards Index</h1>
<div class="container root px-2" >
    <div class="--bs-body-bg: #607d8b;">
            <h4><%= link_to " new card", new_card_path , data: { bs_toggle: "modal", bs_target: "#new-card", remote: :true }, class:"link2"  %></h4> 
            <div class="body">
                <div class="row  name">
                    <% @cards.each do |card|%>
                        <h2 class="color"> name of cards:<%= card.name %> </h2><br>
                             <% card.images.each do |image| %>
                                <div class="card name font  "style="width: 18rem;" >
                                    <center><%= image_tag(url_for(image), style: "width:80%; height:100%") %></center>
                                        <div class="card-body">
                                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                                        </div>
                                        <div class="card-body">
                                            <%=link_to "show card details" , card_path(card.id),remote: :true %>
                                        </div>
                                    </div>
                            <% end %>
                         <%end%>
                    </div>
                </div>
            </div>
        </div>  
</div>

<div class="modal fade" id="new-card" tabindex="-1" aria-labelledby="NewCardModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="NewCardModalLabel">Create card modal</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div id= "card-form">
            </div>
        </div>
    </div>
</div> 

<div  id="show-review"> <%#= render "reviews/showreview", review: @review %></div>


</center>
</div>

<style>
.name{
    margin-left:40px;
}
.color{
    color: #009688;
    font-variant:common-ligatures;
    FONT-WEIGHT: 300;
    FONT-VARIANT: JIS83;
    font-family: Ebrima;
    color: #3f51b5;
   
}
.font{
    color: #009688;
    --bs-body-font-weight: 500;
     font-style: italic;
}
.container{
    --bs-body-bg: #607d8b;
    --bs-body-bg: #758f8c;
}
.link{
    --bs-link-color: #9c27b0;
}
.root{
    --bs-body-font-family: auto;
}
.link2{
    --bs-link-color: #9c27b0;
}

.body {
    font-family: 'Montserrat', sans-serif !important;
}
.px-2 {
  padding-top: ($spacer * .5) !important;
 
}

</style>

app/views/cards/new.js.erb
$("#card-form").html("<%= j render partial: 'form', locals: { card: @card } %>")

app/views/cards/show.js.erb
 $("#card-show").html("<%= j render partial: 'showcard', locals: { card: @card} %>")